platform :ios, '15.0'
use_frameworks!
use_modular_headers!

target 'App' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
